name: flutter_training
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 1.1.6
  cupertino_icons: ^1.0.2
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training.git
      ref: main
      path: packages/yumemi_weather
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_riverpod: ^2.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  blendthink_lints: ^3.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.0
flutter:
  uses-material-design: true
  assets:
    - images/
